### ISSUE TITLE
waterline-cursor@0.0.5 causing undefined attributes to be added when populating association

### ISSUE THREAD

**Issue by AnalogJ** [balderdashy/waterline-cursor#1]
After my most recent deploy of my application, I started running into issues with my app in a staging environment. I traced it back to a version update in the waterline-cursor library. In my development env I'm using 0.0.3, and in staging I see the issue because npm is using 0.0.5 (it goes away if I set a hard dependency on 0.0.3)

Basically I noticed that after a `findOne` query, with a `populate` on a collection, I have an additional `undefined` attribute that points to an empty array. When I comment out the `populate` call, there's no extra attribute. This is occurring with the `sails-postgresql` adapter.

**Comment by mikermcneil** [comment]
@AnalogJ thanks for the heads up- would you mind recreating this for us in a failing test so we can dig deeper?

**Comment by AnalogJ** [comment]
Hey @mikermcneil 
I didnt look into it very deep to figure out the root cause. I'm using my own fork of waterline-postgresql and waterline-cursor to add native array support to postgres, and I just needed to get it working. 

You'll probably want to just close this issue if no one else is reporting any similar problems.

**Comment by devinivy** [comment]
This could be the cause, introduced in v0.0.5: https://github.com/balderdashy/waterline-cursor/commit/bcda0eb4e6b0f07501595a891d3a277712ca67be#diff-9704412c3bc50917cc02255b1b1c37f7R112

**Comment by zapbuild** [comment]
I got the same issue here.. 
Here are the details:
**usertest.js

```
attributes: {
    name:'STRING',
    age:'INTEGER',
    pets:{
        collection: 'pet',
        via: 'owner'
    }
}
```

**pet.js

``` js
  attributes: {
        name:'STRING',
        color:'STRING',
        owner:{
            model:'usertest'
        }
    }
```

**testcontroller.js

``` js
test : function(req,res){
        usertest.find().populate('pets').exec(function(err,r){console.log(r[0].toJSON())});
    }
```

Result, i am getting is

``` js
[ { pets: [],
    name: 'Mike',
    age: 21,
    id: 1,
    createdAt: '2015-06-10T05:16:07.000Z',
    updatedAt: '2015-06-10T05:16:07.000Z',
    undefined: 
     [ { name: 'Pinkie Pie',
         color: 'pink',
         owner: 1,
         id: 1,
         createdAt: '2015-06-10T05:17:23.000Z',
         updatedAt: '2015-06-10T05:17:23.000Z' },
       { name: 'Applejack',
         color: 'orange',
         owner: 1,
         id: 2,
         createdAt: '2015-06-10T05:18:00.000Z',
         updatedAt: '2015-06-10T05:18:00.000Z' } ] } ]
```

Can you please suggest, what is the issue here. Following are the versions, i am working in : 
Sails 0.11.0
Nodejs 0.10.25
NPM 2.11.1

Thanks in advance!

**Comment by dmarcelino** [comment]
@zapbuild, can you provide a failing test? Perhaps in [waterline-adapter-tests - associations - hasMany](https://github.com/balderdashy/waterline-adapter-tests/tree/master/interfaces/associations/hasMany)?
