### ISSUE TITLE
Calling synchronous function in async.eachSeries causes maximum call stack error

### ISSUE THREAD

**Issue by ilia-khaustov** [balderdashy/waterline-cursor#2]
More of this bug here - https://github.com/balderdashy/waterline/issues/733

There is synchronous call in `buildChildBuffers` function in the file `populateBuffers.js`, line 68. This problem is widely covered here - https://github.com/caolan/async/pull/588. I guess it would be enough to change line 68 from `nextParent()` to `async.setImmediate(nextParent)`.

**Comment by mikermcneil** [comment]
> would be enough to change line 68 from nextParent() to async.setImmediate(nextParent).

Perfect- PR welcome, thanks!

**Comment by ilia-khaustov** [comment]
What do you mean by PR? Fun fact: Github is blocked in Russia due to a
number of texts describing suicide methods.

2014-12-04 0:18 GMT+07:00 Mike McNeil notifications@github.com:

**Comment by devinivy** [comment]
I moved your first comment over to #3 where there is some more conversation.  Closing this as a duplicate.

Also, PR stands for "pull request" :)
