### ISSUE TITLE
The forEach loop in Buffer.add function throws " Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by ArVan** [balderdashy/waterline-cursor#3]
I have a `sails-mongo` search query with populate and sorting. In certain conditions it must return about 40K entities. 
Query looks like this:

```
Property.find({id: matchedPropertyIds})
                    .populate('realtor', {status: RowStatus.active})
                    .sort(sortOpt)
                    .exec(function(err, matchedProperties) {
                   });
```

But the app crashes with the error:

```
/srv/nodejs/skupit/node_modules/sails-mongo/node_modules/waterline-cursor/cursor/buffer.js:48
 values.forEach(function(val) {
        ^
RangeError: Maximum call stack size exceeded
```

**Comment by mikermcneil** [comment]
@ArVan awesome, thanks for the heads up.  If you (or anyone else reading this) has a moment to write a failing test, that would help us out a lot.  I've seen you around for a while- if you'd like to get more involved with the project, please let me know (tweet @mikermcneil)

**Comment by bryandent** [comment]
We are getting this error as well.  Our data set is rather small, 12K objects.

**Comment by devinivy** [comment]
From @ilya-khaustov on #2 , which seems to be the same issue:

> More of this bug here - balderdashy/waterline#733
> 
> There is synchronous call in buildChildBuffers function in the file populateBuffers.js, line 68. This problem is widely covered here - caolan/async#588. I guess it would be enough to change line 68 from nextParent() to async.setImmediate(nextParent).

**Comment by wancharle** [comment]
I have this error as well. My data set is rather small, 4k objects.  
The solution from @ilya-khaustov on #2 has solve the problem in my project.

**Comment by devinivy** [comment]
PR #5 posted implementing @ilya-khaustov's fix.
